serokell/o-clock

src/Time/Units.hs, test/Spec.hs, test/Test/Time/TypeSpec.hs
=> [#5] Pretty `Show` instance

src/Time/Units.hs, test/Test/Time/Units.hs
=> [#6] Add creation functions

src/Time/Units.hs, test/Test/Time/Units.hs
=> [#10] Add Read instance

o-clock.cabal, test/Spec.hs, test/Test/Time/ReadShow.hs
=> [#15] Add propperty-based tests for read.show=id

src/Time/Units.hs, test/Test/Time/ReadShow.hs, test/Test/Time/TimeStamp.hs, test/Test/Time/TypeSpec.hs, test/Test/Time/Units.hs
=> [#18] Add more functions

src/Time.hs, src/Time/Rational.hs, src/Time/TimeStamp.hs, src/Time/Units.hs, test/Test/Time/ReadShow.hs, test/Test/Time/TimeStamp.hs, test/Test/Time/TypeSpec.hs, test/Test/Time/Units.hs
Resolves #20
And resolves some haddock issue/warnings.
=> [#20] Refactor unit names

src/Time/Units.hs, test/Spec.hs, test/Test/Time/Units.hs
=> [#24] Rename convertUnit to toUnit

README.lhs, README.md, o-clock.cabal, src/Time/Units.hs
=> [#11] Add function examples and README

README.md, src/Time/Units.hs, test/Test/Time/Units.hs
=> [#25] Add floorUnit function

src/Time/Rational.hs, src/Time/Units.hs
=> Introduce `withDivRat`

src/Time/Rational.hs, src/Time/Units.hs
=> [#36] Introduce KnownDivRat constraint

README.md, src/Time/TimeStamp.hs, src/Time/Units.hs, test/Test/Time/Property.hs, test/Test/Time/TimeStamp.hs, test/Test/Time/Units.hs
=> [#32] Use type equalities in type signatures

test/Test/Time/Property.hs
=> [#41] Use element combinator in property tests

src/Time/Units.hs
=> [#42] Add unitNameVal

benchmark/Main.hs, o-clock.cabal, src/Time/Units.hs
Resolves #33 .
Current results I get:
=> [#33] Add benchmarks with gauge

CHANGELOG.md, README.md, o-clock.cabal, src/Time/Formatting.hs, src/Time/Rational.hs, src/Time/Units.hs, stack.yaml, test/Test/Time/Property.hs, test/Test/Time/TypeSpec.hs
I'm not very happy with how code looks now, but I don't know the prettier way..
Resolves #29 .
=> [#29] Support ghc-8.2.2 with stack

CHANGELOG.md, o-clock.cabal, src/Time/Formatting.hs, test/Test/Time/Units.hs
=> [#45] Fix behavior of 0 time passed to seriesF

CHANGELOG.md, src/Time/Formatting.hs, src/Time/Rational.hs, test/Test/Time/TypeSpec.hs
=> [#51] Verify seriesF

CHANGELOG.md, o-clock.cabal, src/Time/Bool.hs, src/Time/Formatting.hs, src/Time/Rational.hs, src/Time/TimeStamp.hs, src/Time/Units.hs
=> [#46] Introduce ... type for lists creation

CHANGELOG.md, o-clock.cabal, src/Time/Formatting.hs, src/Time/Units.hs, test/Doctest.hs
=> [#56] Add doctest support

CHANGELOG.md, o-clock.cabal, src/Time/Formatting.hs, src/Time/Rational.hs, src/Time/TimeStamp.hs, src/Time/Units.hs
=> [#72] Enhance TimeStamp, refactor

CHANGELOG.md, o-clock.cabal, src/Time/TimeStamp.hs, test/Test/Time/TimeStamp.hs
=> [#76] Make TimeStamp work with Seconds internally

CHANGELOG.md, README.md, src/Time/Formatting.hs
=> [#60] Modify Series to show fraction in the last arg

CHANGELOG.md, src/Time/TimeStamp.hs
=> [#70] Add fromReal function

CHANGELOG.md, src/Time/TimeStamp.hs
=> Revert "[#70] Add fromReal function"

.gitignore, CHANGELOG.md, o-clock.cabal, src/Time.hs, src/Time/Formatting.hs, src/Time/Timestamp.hs, test/Spec.hs, test/Test/Time/Timestamp.hs
=> [#81] Rename TimeStamp to Timestamp

CHANGELOG.md, src/Time/Units.hs
=> [#71] Add toNum function

CHANGELOG.md, src/Time/Timestamp.hs
=> [#85] Add fromUnixTime function

.gitignore, CHANGELOG.md, o-clock.cabal, src/Time/Units.hs
=> [#95] Add Semigroup and Monoid instances for Time

CHANGELOG.md, o-clock.cabal
=> [#93] Remove transformers dependency

CHANGELOG.md, README.md, benchmark/Main.hs, o-clock.cabal, src/Time/Units.hs, stack-8.0.2.yaml, stack.yaml
=> [#100] Add instances

.travis.yml, CHANGELOG.md, README.md, cabal.project.local.ubuntu-example, examples/Playground.hs, o-clock.cabal, src/Time/Series.hs, src/Time/Timestamp.hs, src/Time/Units.hs, stack.yaml, test/Test/Time/Timestamp.hs, test/Test/Time/Units.hs
=> [#106] Remove Num and related instances for Time

CHANGELOG.md, o-clock.cabal
Port of #115 to a newer master (with fixed CI) + a commit to prepare a new release.
=> Allow tasty-1.4

.github/workflows/ci.yml, o-clock.cabal, stack.yaml
Simple maintenance PR that just updates some versions. I suppose we don't need a new release for it, we can just make a new revision.
=> Update doctest upper bound and some configuration

o-clock.cabal
=> Allow building with GHC 9.0.1

o-clock.cabal
Update upper bound for `tasty-hedgehog`.
None
Ideally a PR has all of the checkmarks set.
If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).
- Tests
silently reappearing again.
- Documentation
- [README](https://github.com/serokell/o-clock/tree/master/README.md)
- Haddock
- Public contracts
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
and
under the "Unreleased" section to a new section for this release version.
I added [`@since` haddock annotations](https://haskell-haddock.readthedocs.io/en/latest/markup.html#since).
with a summary of all user-facing changes.
*  I made sure a tag was created using the …
=> [Chore] Update upper bound for `tasty-hedgehog`

.github/workflows/ci.yml
Update xrefcheck to v0.2.2. Also switch GitHub actions to newer versions.
None
Ideally a PR has all of the checkmarks set.
If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).
- Tests
silently reappearing again.
- Documentation
- [README](https://github.com/serokell/o-clock/tree/master/README.md)
- Haddock
- Public contracts
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
and
=> [Chore] Update xrefcheck to v0.2.2

.github/workflows/ci.yml
Update `ci.yml` to use `xrefcheck-0.3.1`
=> [Chore] Update to xrefcheck-0.3.1
